### PR TITLE
🛁 Cleaned up some unused dependencies and froze everything else

### PR DESCRIPTION
**Pull request by 0xjjpa**
Hey there! So after updating the latest version of `dev`, could help to see that there were a couple replicated packages there. Furthermore, it's good practice to freeze dependencies as have `^` can easily break the project in the future. A good example is `web3`, which currently works for `1.0.0-beta.37`, but currently has a couple inconsistencies from `1.0.0-beta.45+`. If anyone where to newly install your dependencies, it might install some that are not going to work in the future.

So, this pull-request does a couple things:

* Freezes your current dependencies.
* Removes unused dependencies.

## Additional notes

Now, removing dependencies isn't a straightforward process. You might be using something it's actually there, but I just couldn't picked up. Here's my process for detecting unused dependencies, and which ones I've removed or not.

### Step one, review unchecked packages

I ran `npx npm-check-unused`, which reviews `package.json` and imports across the entire project to see if there are any inconsistencies or unused packages. You can read more about how it works [here](https://www.npmjs.com/package/npm-check-unused). It gives me a good list of candidates to check and review, to which I then go to the next step.

### Step two, frequency detection

I ran `grep --exclude-dir=node_modules -rni $PACKAGE .` where `$PACKAGE` is each of your 
 dependencies listed previously by `npm-check-unused`. This allowed me to see whether you had been actually using it or not. `openzeppelin-solidity` will show up in `npm-check-unused` but it's obviously being used. `solidity-coverage` is being called via `spawnSync` so it wasn't picked up by npm. Some packages like `libp2p-crypto-secp256k1` are tricky, since I can't find any repetition, but 
 aren't probably called directly as a package and instead as a command. Another one is `libp2p-switch`, which isn't really imported but is mentioned a couple times. Thus, as long as they are 
 mentioned in any other file that `yarn.lock` and `package.json`, they remain.

## Removed packages

At the end, found out the following packages are no longer used and are probably no longer required, they were most likely imported in previous versions of the project.

- bignumber.js
- chalk-animation
- libp2p-spdy
- libp2p-switch
- lodash.differencewith
- lodash.uniqby
- socket.io

Every other package has been frozen. For ensuring removing this packages does not affect the project, I would recommend pulling this branch, removing `node_modules`, running `yarn` and running the usual commands.

### CODE REVIEW

**Comment by 0xjjpa** [comment]
@robertkiel didn't see your latest update! Just added a new commit with your latest changes so your package upgrades are also included here.

**Comment by SCBuergel** [comment]
Wonderful, thanks for the cleaning up efforts and locking versions!

**Comment by robertkiel** [comment]
@jjperezaguinaga thank you very much. I did a lot of cleanup in the repository today and integrated most of your changes. Since a lot of projects regularly come along with small bug fixes, I decided to pin their version by using `<packagename>: ~<VERSION>` which allows small version changes according to `semver`, e.g. from `0.4.23` to `0.4.25` but not from `0.4.23` to `0.5.x`

Some explanation to the dependencies:
- `libp2p-crypto` tries to load `libp2p-crypto-secp256k1` and enables the elliptic curve crypto functionality in case it finds the package.
- `libp2p-switch` was necessary because I've forked it for a while until they've integrated some changes, same for `pull-length-prefixed`

`solidity-coverage` is part of our smart contract testing suite. I think, I'll remove that one in a near future.

**Comment by 0xjjpa** [comment]
@robertkiel no worries! As long as you picked up the changes, I'm happy either way. Going to leave the branch there for a bit, and will remove it after 30 days if we no longer need it.

Noticed `solidity-coverage`, it's being used, it's just that it isn't called by a library and instead by `spawnSync` so I think that one is fine. My only problem with `solidity-coverage` is that sometimes it seems to use a different runtime/compiler and sometimes it has some `runOutOfGas` exceptions.

Regarding pinning with `~`, I was unaware of that, and sounds like a great choice! Will keep poking around to see if I can help with anything else.

**Comment by 0xjjpa** [comment]
Branch removed! 🎉

**Pull request closed without merging**
